JGraph.Draw
Git.Git
nomacs.nomacs
M2Team.NanaZip
Zen-Team.Zen-Browser
Brave.Brave
Notepad++.Notepad++
Starpine.Screenbox
WireGuard.WireGuard
Nextcloud.NextcloudDesktop
Microsoft.OpenSSH.Beta
Adobe.Acrobat.Pro
gerardog.gsudo
Adobe.CreativeCloud
OpenWhisperSystems.Signal
Telegram.TelegramDesktop
Microsoft.Teams
JanDeDobbeleer.OhMyPosh
Microsoft.OneDrive
Obsidian.Obsidian
Proton.ProtonMail
Proton.ProtonDrive
ShareX.ShareX
Flow-Launcher.Flow-Launcher
voidtools.Everything
okibcn.nano
Proton.ProtonPass
glzr-io.glazewm
